blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name ="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name="home"),
    # A la vista se llama a la funcion as_view() por que 
    #  despues sale un error 

    path('blog/', include('blog.urls', namespace='blog'))

    
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

#Formulario para crear un post 
class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from turtle import title
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        # Para listar primero llamamos a los Post de la BD
        posts = Post.objects.all()
        context = {
            'posts':posts
            #El primer posts es el nombre con el que 
            #vamos a llamar al html y el segundo la variable
            # que creamos posts = Post.objects.all()
        }
        return render(request,'blog_list.html', context)


# La vista del PostCreateForm
"""
METODO GET: Es todo el requerimiento que se le pide 
al servidor para mostrar la informacion al usuario 

METODO POST: Es todo requerimiento que se le pide al 
usuario 

"""
class BlogCreateView(View): 
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context = {
            'form':form
            #'Form' es el nombre con el que puedo 
            #llamar en el html a lo que hay dentro del 
            # PostCraeteForm
            #Que es el titulo y content del post a crear
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST":

            """
            Si al enviar es un metodo post se llama al
            formulario con el requerimiento post 

            """
            form = PostCreateForm(request.POST)

            
            if form.is_valid():
                # Si el form es valido queremos obtener el contenido
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                #Creamos el post 
                p, created = Post.objects.get_or_create(title=title, content=content)
                """ 
                El title y el content de la izquierda vienen del post de modelos.py
                que contiene un title y un content.

                Los de la derecha vienen del title = form.cleaned_data de aqui
                lo que estamos diciendole es que guarde la info que se obtuvo 
                en el formulario 

                """
                #Guardamos todo 
                p.save() 
                return redirect('blog:home')

        context = {
            
        }
        return render(request, 'blog_create.html', context)

class BlogDetailView(View):
    # Una vez registrado el pk en urls podemos hacer uso 
    def get(self, request, pk, *args, **kwargs):
        """ 
        Esta variable post llama al post con cierto id
        en caso que no exista llama la pagina que contiene 
        el error 404
        
        """
        post = get_object_or_404(Post, pk=pk)
        context = {
            "post":post
        }
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        # Referenciamos al id del post 
        """
        self.kwargs es la informacion que esta dentro 
        del dato que estamos llamando en este caso pk 

        """
        pk = self.kwargs['pk']
        # Usamos el kwargs pk para refrescar el detail del blog 
        return reverse_lazy('blog:detail', kwargs={'pk':pk})


class BlogDeleteView(DeleteView):
    model = Post
    template_name= 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
# urlCONF
from django.views.generic import View
from django.shortcuts import render 

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css %}

    <title>Document</title>
</head>
<body>
    
    {% block content %}{% endblock content %}

</body>
</html>

templates/blog_create.html
<h1> Blog create </h1>

<br>

<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<br>
<button type="submit">Submit</button>
</form>

templates/blog_delete.html
<h1> Blog delete </h1>

<br>

<h2>Are you sure?</h2>

<br>

<form method="POST">
{% csrf_token %}
{{form}}
<br>
<button type="submit">Delete</button>
</form>

templates/blog_detail.html
<h1> DETAIL BLOG  </h1>

{{post.title}}

<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}

{% block content %}


    <h1> Bienvenido a la lista de los blogs </h1>

    <br>

    {% for post in posts%}


        <a href="{% url 'blog:detail' post.id %}" >{{post.title}}</a>
        <a href="{% url 'blog:update' post.id %}" >Update {{post.title}}</a>
        <a href="{% url 'blog:delete' post.id %}" >Delete {{post.title}}</a>

    {% endfor %}

    <br>
    <br>
    <br>

    <a class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" href="{% url 'blog:create' %}">Create</a>

{% endblock content %}

templates/blog_update.html
<h1> Blog update </h1>

<br>

<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<br>
<button type="submit">Update</button>
</form>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1> Este es mi home </h1>
    <h2>HOLA visita mi 
        <a class="text-blue-500" href="{% url 'blog:home' %}"> blog  aqui </a>  
    </h1>
    <!-- Para la url hacer referencia al namespace de core 
        luego al name de blog -->


{% endblock content %}




    

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>